// Lista de bancos conforme Banco Central do Brasil
export const BANCOS = [
  { cod: '001', nome: 'Banco do Brasil' },
  { cod: '003', nome: 'Banco da Amazônia' },
  { cod: '004', nome: 'Banco do Nordeste do Brasil' },
  { cod: '007', nome: 'BNDES' },
  { cod: '010', nome: 'Credicoamo' },
  { cod: '011', nome: 'Credit Suisse Hedging-Griffo' },
  { cod: '012', nome: 'Banco Inbursa' },
  { cod: '014', nome: 'Natixis Brasil' },
  { cod: '015', nome: 'UBS Brasil' },
  { cod: '016', nome: 'Coop de Créd. Mútuo dos Despachantes de Trânsito' },
  { cod: '017', nome: 'BNY Mellon Banco' },
  { cod: '018', nome: 'Banco Tricury' },
  { cod: '021', nome: 'Banestes' },
  { cod: '024', nome: 'Banco BANDEPE' },
  { cod: '025', nome: 'Banco Alfa' },
  { cod: '029', nome: 'Banco Itaú Consignado' },
  { cod: '033', nome: 'Santander' },
  { cod: '036', nome: 'Banco Bradesco BBI' },
  { cod: '037', nome: 'Banco do Estado do Pará' },
  { cod: '040', nome: 'Banco Cargill' },
  { cod: '041', nome: 'Banrisul' },
  { cod: '047', nome: 'Banco do Estado de Sergipe' },
  { cod: '060', nome: 'Confidence Câmbio' },
  { cod: '062', nome: 'Hipercard Banco Múltiplo' },
  { cod: '063', nome: 'Banco Bradescard' },
  { cod: '064', nome: 'Goldman Sachs do Brasil' },
  { cod: '065', nome: 'Banco AndBank' },
  { cod: '066', nome: 'Banco Morgan Stanley' },
  { cod: '069', nome: 'Banco Crefisa' },
  { cod: '070', nome: 'BRB - Banco de Brasília' },
  { cod: '074', nome: 'Banco J. Safra' },
  { cod: '075', nome: 'Banco ABN Amro' },
  { cod: '076', nome: 'Banco KDB do Brasil' },
  { cod: '077', nome: 'Banco Inter' },
  { cod: '078', nome: 'Haitong Banco de Investimento do Brasil' },
  { cod: '079', nome: 'Banco Original do Agronegócio' },
  { cod: '080', nome: 'B&T Câmbio' },
  { cod: '081', nome: 'BBN Banco Brasileiro de Negócios' },
  { cod: '082', nome: 'Banco Topázio' },
  { cod: '083', nome: 'Banco da China Brasil' },
  { cod: '084', nome: 'Uniprime Norte do Paraná' },
  { cod: '085', nome: 'Cooperativa Central de Crédito - Ailos' },
  { cod: '088', nome: 'Banco Randon' },
  { cod: '089', nome: 'Credisan' },
  { cod: '091', nome: 'Unicred do Brasil' },
  { cod: '092', nome: 'BRK' },
  { cod: '093', nome: 'Polocred' },
  { cod: '094', nome: 'Banco Finaxis' },
  { cod: '095', nome: 'Travelex Banco de Câmbio' },
  { cod: '096', nome: 'Banco B3' },
  { cod: '097', nome: 'Credisis' },
  { cod: '098', nome: 'Credialiança' },
  { cod: '099', nome: 'Uniprime Central' },
  { cod: '100', nome: 'Planner Corretora de Valores' },
  { cod: '101', nome: 'Renascença DTVM' },
  { cod: '102', nome: 'XP Investimentos' },
  { cod: '104', nome: 'Caixa Econômica Federal' },
  { cod: '105', nome: 'Lecca Crédito' },
  { cod: '107', nome: 'Banco BOCOM BBM' },
  { cod: '108', nome: 'PortoCred' },
  { cod: '111', nome: 'Oliveira Trust DTVM' },
  { cod: '113', nome: 'Magliano' },
  { cod: '114', nome: 'Central Cooperativa de Crédito no Estado do Espírito Santo' },
  { cod: '117', nome: 'Advanced Corretora de Câmbio' },
  { cod: '118', nome: 'Standard Chartered Bank' },
  { cod: '119', nome: 'Banco Western Union do Brasil' },
  { cod: '120', nome: 'Banco Rodobens' },
  { cod: '121', nome: 'Banco Agiplan' },
  { cod: '122', nome: 'Banco Bradesco BERJ' },
  { cod: '124', nome: 'Banco Woori Bank do Brasil' },
  { cod: '125', nome: 'Brasil Plural Banco Múltiplo' },
  { cod: '126', nome: 'BR Partners Banco de Investimento' },
  { cod: '127', nome: 'Codepe CVC' },
  { cod: '128', nome: 'MS Bank' },
  { cod: '129', nome: 'UBS Brasil Banco de Investimento' },
  { cod: '130', nome: 'Caruana' },
  { cod: '131', nome: 'Tullett Prebon Brasil' },
  { cod: '132', nome: 'ICBC do Brasil' },
  { cod: '133', nome: 'Cresol' },
  { cod: '134', nome: 'BGC Liquidez DTVM' },
  { cod: '136', nome: 'Unicred' },
  { cod: '138', nome: 'Get Money CC' },
  { cod: '139', nome: 'Intesa Sanpaolo Brasil' },
  { cod: '140', nome: 'Easynvest - Título CV' },
  { cod: '141', nome: 'Broker Brasil CC' },
  { cod: '142', nome: 'Broker Brasil CC' },
  { cod: '143', nome: 'Treviso CC' },
  { cod: '144', nome: 'Bexs Banco de Câmbio' },
  { cod: '145', nome: 'Levycam CCV' },
  { cod: '146', nome: 'Guitta CC' },
  { cod: '149', nome: 'Facta Financeira' },
  { cod: '157', nome: 'ICAP do Brasil CTVM' },
  { cod: '159', nome: 'Casa do Crédito' },
  { cod: '163', nome: 'Commerzbank Brasil' },
  { cod: '173', nome: 'BRL Trust DTVM' },
  { cod: '174', nome: 'Pernambucanas Financiadora' },
  { cod: '177', nome: 'Guide Investimentos' },
  { cod: '180', nome: 'CM Capital Markets CCTVM' },
  { cod: '182', nome: 'Dacasa Financeira' },
  { cod: '183', nome: 'Socred' },
  { cod: '184', nome: 'Banco Itaú BBA' },
  { cod: '188', nome: 'Ativa Investimentos' },
  { cod: '189', nome: 'HS Financeira' },
  { cod: '190', nome: 'Servicoop' },
  { cod: '191', nome: 'Nova Futura CTVM' },
  { cod: '194', nome: 'Parmetal Distribuidora e Corretora de Câmbio' },
  { cod: '195', nome: 'Icap do Brasil CTVM' },
  { cod: '196', nome: 'Fair CC' },
  { cod: '197', nome: 'Stone Pagamentos' },
  { cod: '208', nome: 'Banco BTG Pactual' },
  { cod: '212', nome: 'Banco Original' },
  { cod: '213', nome: 'Banco Arbi' },
  { cod: '217', nome: 'Banco John Deere' },
  { cod: '218', nome: 'Banco BS2' },
  { cod: '222', nome: 'Banco Credit Agricole Brasil' },
  { cod: '224', nome: 'Banco Fibra' },
  { cod: '225', nome: 'Banco Brascan' },
  { cod: '229', nome: 'Banco Cruzeiro do Sul' },
  { cod: '230', nome: 'Unicard Banco Múltiplo' },
  { cod: '233', nome: 'Banco Cifra' },
  { cod: '237', nome: 'Bradesco' },
  { cod: '241', nome: 'Banco Clássico' },
  { cod: '243', nome: 'Banco Máxima' },
  { cod: '246', nome: 'Banco ABC Brasil' },
  { cod: '249', nome: 'Banco Investcred Unibanco' },
  { cod: '250', nome: 'BCV' },
  { cod: '251', nome: 'Parana Banco' },
  { cod: '253', nome: 'Bexs Corretora de Câmbio' },
  { cod: '254', nome: 'Paraná Banco' },
  { cod: '259', nome: 'MONEYCORP Banco de Câmbio' },
  { cod: '260', nome: 'Nu Pagamentos (Nubank)' },
  { cod: '265', nome: 'Banco Fator' },
  { cod: '266', nome: 'Banco Cédula' },
  { cod: '268', nome: 'Barigui Companhia Hipotecária' },
  { cod: '269', nome: 'HSBC Brasil Banco de Investimento' },
  { cod: '270', nome: 'Sagitur CC' },
  { cod: '271', nome: 'IB CCTVM' },
  { cod: '272', nome: 'AGK CC' },
  { cod: '273', nome: 'CCR de São Miguel do Oeste' },
  { cod: '274', nome: 'BMP Money Plus SCMEPP' },
  { cod: '276', nome: 'Senff' },
  { cod: '278', nome: 'Genial Investimentos CVM' },
  { cod: '279', nome: 'CCR de Primavera do Leste' },
  { cod: '280', nome: 'Avista' },
  { cod: '281', nome: 'CCR Coopavel' },
  { cod: '283', nome: 'RB Capital Investimentos DTVM' },
  { cod: '285', nome: 'Frente CC' },
  { cod: '286', nome: 'CCR de Ouro' },
  { cod: '288', nome: 'Carol DTVM' },
  { cod: '289', nome: 'EFX CC' },
  { cod: '290', nome: 'Pagseguro Internet' },
  { cod: '292', nome: 'BS2 Distribuidora de Títulos e Valores Mobiliários' },
  { cod: '293', nome: 'Lastro RDV DTVM' },
  { cod: '296', nome: 'OZ Corretora de Câmbio' },
  { cod: '298', nome: 'Vips CC' },
  { cod: '299', nome: 'Sorocred' },
  { cod: '300', nome: 'Banco de la Nacion Argentina' },
  { cod: '301', nome: 'BPP Instituição de Pagamento' },
  { cod: '306', nome: 'Portopar DTVM' },
  { cod: '307', nome: 'Terra Investimentos DTVM' },
  { cod: '309', nome: 'Cambionet CC' },
  { cod: '310', nome: 'VORTX DTVM' },
  { cod: '315', nome: 'PI Distribuidora de Títulos e Valores Mobiliários' },
  { cod: '318', nome: 'Banco BMG' },
  { cod: '319', nome: 'OM DTVM' },
  { cod: '320', nome: 'China Construction Bank' },
  { cod: '321', nome: 'Crefaz SCMEPP' },
  { cod: '322', nome: 'Cooperativa de Crédito Rural de Abelardo Luz' },
  { cod: '323', nome: 'Mercado Pago' },
  { cod: '324', nome: 'Cartos SCD' },
  { cod: '325', nome: 'Órama DTVM' },
  { cod: '326', nome: 'Parati CFI' },
  { cod: '329', nome: 'QI Sociedade de Crédito Direto' },
  { cod: '330', nome: 'Banco Bari de Investimentos e Financiamentos' },
  { cod: '331', nome: 'Fram Capital DTVM' },
  { cod: '332', nome: 'Acesso Soluções de Pagamento' },
  { cod: '335', nome: 'Banco Digio' },
  { cod: '336', nome: 'Banco C6' },
  { cod: '340', nome: 'Super Pagamentos e Administração de Meios Eletrônicos' },
  { cod: '341', nome: 'Itaú Unibanco' },
  { cod: '342', nome: 'Creditas SCD' },
  { cod: '343', nome: 'FFA SCMEPP' },
  { cod: '348', nome: 'Banco XP' },
  { cod: '349', nome: 'AL5 SCD' },
  { cod: '350', nome: 'Cooperativa de Crédito Rural de Pequenos Agricultores e da Reforma Agrária' },
  { cod: '352', nome: 'Toro CTVM' },
  { cod: '354', nome: 'Necton Investimentos' },
  { cod: '355', nome: 'Ótimo SCD' },
  { cod: '358', nome: 'MIDWAY' },
  { cod: '359', nome: 'Zema CFI' },
  { cod: '360', nome: 'Trinus Capital DTVM' },
  { cod: '362', nome: 'Cielo' },
  { cod: '363', nome: 'Singulare CTVM' },
  { cod: '364', nome: 'Gerencianet' },
  { cod: '365', nome: 'Simpaul' },
  { cod: '366', nome: 'Banco Societe Generale Brasil' },
  { cod: '367', nome: 'Vitreo DTVM' },
  { cod: '368', nome: 'Banco CSF' },
  { cod: '370', nome: 'Banco Mizuho do Brasil' },
  { cod: '371', nome: 'Warren CVMC' },
  { cod: '373', nome: 'UP.p SEP' },
  { cod: '374', nome: 'Realize CFI' },
  { cod: '376', nome: 'Banco J.P. Morgan' },
  { cod: '377', nome: 'BMS SCD' },
  { cod: '378', nome: 'BBC Digital SCD' },
  { cod: '379', nome: 'Cecap CC' },
  { cod: '380', nome: 'PicPay Serviços' },
  { cod: '381', nome: 'Banco Mercedes-Benz do Brasil' },
  { cod: '382', nome: 'Fiducia SCMEPP' },
  { cod: '383', nome: 'Ebanx IP' },
  { cod: '384', nome: 'Global SCM' },
  { cod: '385', nome: 'Cooperativa de Economia e Crédito Mútuo dos Trabalhadores' },
  { cod: '386', nome: 'Nu Financeira' },
  { cod: '387', nome: 'Banco Toyota do Brasil' },
  { cod: '389', nome: 'Banco Mercantil do Brasil' },
  { cod: '390', nome: 'Banco GM' },
  { cod: '391', nome: 'CCR de Ibiam' },
  { cod: '393', nome: 'Banco Volkswagen' },
  { cod: '394', nome: 'Banco Bradesco Financiamentos' },
  { cod: '395', nome: 'F D Gold DTVM' },
  { cod: '396', nome: 'HUB IP' },
  { cod: '397', nome: 'Listo SCD' },
  { cod: '398', nome: 'Ideal CTVM' },
  { cod: '399', nome: 'Kirton Bank' },
  { cod: '400', nome: 'Cooperativa de Crédito Rural de Mato Grosso - Credimato' },
  { cod: '401', nome: 'Iugu IP' },
  { cod: '402', nome: 'Cobuccio SCD' },
  { cod: '403', nome: 'Cora SCD' },
  { cod: '404', nome: 'Sumup SCD' },
  { cod: '406', nome: 'Accredito SCD' },
  { cod: '407', nome: 'Índigo Investimentos DTVM' },
  { cod: '408', nome: 'Bonuspago SCD' },
  { cod: '410', nome: 'Planner Sociedade de Crédito ao Microempreendedor' },
  { cod: '411', nome: 'Via Certa Financiadora' },
  { cod: '412', nome: 'Banco Capital' },
  { cod: '413', nome: 'Banco BV' },
  { cod: '414', nome: 'Work SCD' },
  { cod: '416', nome: 'Lamara SCD' },
  { cod: '418', nome: 'Zipdin SCD' },
  { cod: '419', nome: 'Numbrs SCD' },
  { cod: '421', nome: 'Celcoin IP' },
  { cod: '422', nome: 'Banco Safra' },
  { cod: '423', nome: 'Coluna SCD' },
  { cod: '425', nome: 'Socinal' },
  { cod: '426', nome: 'Biorc Financeira' },
  { cod: '427', nome: 'Cresol Confederação' },
  { cod: '428', nome: 'Credsystem SCD' },
  { cod: '429', nome: 'Crediare CFI' },
  { cod: '430', nome: 'Cooperativa de Crédito Rural Seara' },
  { cod: '431', nome: 'Fnex CC' },
  { cod: '433', nome: 'Mérito DTVM' },
  { cod: '435', nome: 'Delcred SCD' },
  { cod: '438', nome: 'Planner Trustee DTVM' },
  { cod: '439', nome: 'ID CTVM' },
  { cod: '440', nome: 'Credibelo SCD' },
  { cod: '441', nome: 'Magnetis DTVM' },
  { cod: '442', nome: 'Btg Pactual Consignado' },
  { cod: '443', nome: 'Credihome SCD' },
  { cod: '444', nome: 'Trinus SCD' },
  { cod: '445', nome: 'Plantae CFI' },
  { cod: '447', nome: 'Mirae Asset CCTVM' },
  { cod: '448', nome: 'Hemera DTVM' },
  { cod: '449', nome: 'Dmcard SCD' },
  { cod: '450', nome: 'Fitbank IP' },
  { cod: '451', nome: 'J17 SCD' },
  { cod: '452', nome: 'Credifit SCD' },
  { cod: '453', nome: 'Mérito Prev DTVM' },
  { cod: '454', nome: 'Mérito SCD' },
  { cod: '455', nome: 'Fênix DTVM' },
  { cod: '456', nome: 'Banco MUFG Brasil' },
  { cod: '457', nome: 'UY3 SCD' },
  { cod: '458', nome: 'Hedge Investments DTVM' },
  { cod: '459', nome: 'CCM Desp. Trânsito SC e RS' },
  { cod: '460', nome: 'Unavanti SCD' },
  { cod: '461', nome: 'Asaas IP' },
  { cod: '462', nome: 'Stark SCD' },
  { cod: '463', nome: 'Azumi DTVM' },
  { cod: '464', nome: 'Banco Sumitomo Mitsui Brasileiro' },
  { cod: '465', nome: 'Capital Consig SCD' },
  { cod: '467', nome: 'Master SCD' },
  { cod: '468', nome: 'Portoseg CFI' },
  { cod: '469', nome: 'Picrede SCD' },
  { cod: '470', nome: 'CDC SCD' },
  { cod: '471', nome: 'Cooperativa de Crédito Rural de Não-Me-Toque' },
  { cod: '473', nome: 'Banco Caixa Geral Brasil' },
  { cod: '474', nome: 'Banco Citibank' },
  { cod: '475', nome: 'Banco Intermedium' },
  { cod: '476', nome: 'Banco Rendimento' },
  { cod: '477', nome: 'Citibank' },
  { cod: '478', nome: 'Gazincred SCD' },
  { cod: '479', nome: 'Banco ItauBank' },
  { cod: '481', nome: 'Superlógica SCD' },
  { cod: '482', nome: 'SBCASH SCD' },
  { cod: '484', nome: 'MAF DTVM' },
  { cod: '485', nome: 'Juno' },
  { cod: '487', nome: 'Deutsche Bank' },
  { cod: '488', nome: 'JPMorgan Chase Bank' },
  { cod: '489', nome: 'Banco Investcred' },
  { cod: '490', nome: 'MixPag IP' },
  { cod: '495', nome: 'Banco de La Provincia de Buenos Aires' },
  { cod: '505', nome: 'Banco Credit Suisse' },
  { cod: '506', nome: 'RJI Corretora de Títulos e Valores Mobiliários' },
  { cod: '507', nome: 'Scfi SCD' },
  { cod: '508', nome: 'Mr. Pay IP' },
  { cod: '509', nome: 'Celcoin IP' },
  { cod: '510', nome: 'Ffcred SCD' },
  { cod: '511', nome: 'Magnum SCD' },
  { cod: '512', nome: 'Sumup SCD' },
  { cod: '516', nome: 'Qista SCD' },
  { cod: '545', nome: 'Senso CCVM' },
  { cod: '600', nome: 'Banco Luso Brasileiro' },
  { cod: '604', nome: 'Banco Industrial do Brasil' },
  { cod: '610', nome: 'Banco VR' },
  { cod: '611', nome: 'Banco Paulista' },
  { cod: '612', nome: 'Banco Guanabara' },
  { cod: '613', nome: 'Banco Pecúnia' },
  { cod: '620', nome: 'Banco Crédit Agricole Brasil' },
  { cod: '623', nome: 'Banco PAN' },
  { cod: '626', nome: 'Banco Ficsa' },
  { cod: '630', nome: 'Banco Intercap' },
  { cod: '633', nome: 'Banco Rendimento' },
  { cod: '634', nome: 'Banco Triangulo' },
  { cod: '637', nome: 'Banco Sofisa' },
  { cod: '643', nome: 'Banco Pine' },
  { cod: '652', nome: 'Itaú Unibanco Holding' },
  { cod: '653', nome: 'Banco Indusval' },
  { cod: '654', nome: 'Banco A.J. Renner' },
  { cod: '655', nome: 'Banco Votorantim' },
  { cod: '707', nome: 'Banco Daycoval' },
  { cod: '712', nome: 'Banco Ourinvest' },
  { cod: '719', nome: 'Banif' },
  { cod: '720', nome: 'Banco RNX' },
  { cod: '739', nome: 'Banco Cetelem' },
  { cod: '741', nome: 'Banco Ribeirão Preto' },
  { cod: '743', nome: 'Banco Semear' },
  { cod: '745', nome: 'Citibank' },
  { cod: '746', nome: 'Banco Modal' },
  { cod: '747', nome: 'Banco Rabobank Internacional Brasil' },
  { cod: '748', nome: 'Sicredi' },
  { cod: '751', nome: 'Scotiabank Brasil' },
  { cod: '752', nome: 'Banco BNP Paribas Brasil' },
  { cod: '753', nome: 'Novo Banco Continental' },
  { cod: '754', nome: 'Banco Sistema' },
  { cod: '755', nome: 'Bank of America Merrill Lynch' },
  { cod: '756', nome: 'Sicoob' },
  { cod: '757', nome: 'KEB HanA do Brasil' },
]

export const BANCOS_OPTIONS = BANCOS.map(b => ({
  value: `${b.nome} - ${b.cod}`,
  label: `${b.nome} - ${b.cod}`
}))
